spring:
  data:
    redis:
      host: 47.108.58.72
      port: 6379
      database: 0
      timeout: 30s
      lettuce:
        pool:
          max-active: 8       # 最大活跃连接数
          max-idle: 8         # 最大空闲连接数
          min-idle: 0         # 最小空闲连接数