spring:
  redis:
    host: 47.108.58.72       # Redis 服务器地址
    port: 6379              # 端口
    database: 0             # 数据库索引
    timeout: 30s            # 连接超时时间
    lettuce:
      pool:
        max-active: 8       # 最大活跃连接数
        max-idle: 8         # 最大空闲连接数
        min-idle: 0         # 最小空闲连接数