xxl:
  job:
    admin:
      addresses: http://119.45.4.154:9001/xxl-job-admin
    accessToken: "mikasa"
    executor:
      appname: blog-xxljob
      ip:       # 留空由系统自动生成
      port: 9998  # 固定端口，用于执行器通信
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 3